AllCops:
  TargetRubyVersion: 2.5
  DisplayCopNames: true
  DisplayStyleGuide: true

Layout/IndentArray:
  EnforcedStyle: consistent

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Layout/MultilineOperationIndentation:
  EnforcedStyle: indented

Metrics/AbcSize:
  Max: 25
  Exclude:
    - 'test/**/*'

Metrics/BlockLength:
  Exclude:
    - 'literate-launch.gemspec'
    - 'test/**/*.rb'

Metrics/ClassLength:
  Max: 150
  Exclude:
    - 'test/**/*'

Metrics/LineLength:
  Max: 100
  Exclude:
    - 'Gemfile*'
    - 'test/**/*.rb'

Metrics/MethodLength:
  Max: 20
  Exclude:
    - 'test/**/*'

Style/Documentation:
  Enabled: false

Style/DocumentationMethod:
  Enabled: true

Style/ParallelAssignment:
  Enabled: false

Style/RegexpLiteral:
  EnforcedStyle: mixed

Style/SymbolArray:
  EnforcedStyle: percent
  MinSize: 5

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: consistent_comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: consistent_comma
